# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: William C. Dawn
email: wcdawn@ncsu.edu
description: >- # this means to ignore newlines until "baseurl:"
  Ph.D. candidate studying Nuclear Engineering.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wcdawn.github.io" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  wcdawn

linkedin_username: william-dawn-a9838196
linkedin_name: "LinkedIn"

google_scholar_username: 6m4SWJEAAAAJ

researchgate_username: William-Dawn

orcid: 0000-0002-6226-3143


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
